-- B1 — general size/variant model.
--
-- Built general on purpose: a "size" is just a named row, so amostras become
-- another size later rather than a second mechanism bolted on beside this one.
--
-- Pricing is derived-by-default, overridable per product. product_sizes.price_pct
-- gives the rule (100 ml = 100%, 50 ml = 75%, 35 ml = 55%), and
-- product_variants.price holds an override when one size needs its own number.
-- null there means "follow the percentage", which is what keeps a base price
-- change repricing everything.

-- ---------------------------------------------------------------- sizes ---
create table if not exists public.product_sizes (
  id          smallint primary key,
  label       text     not null,
  volume_ml   integer  not null,
  -- Percentage of the product's base price. 100 for the size the base price
  -- refers to. numeric, not integer: 62.5% has to be expressible.
  price_pct   numeric(6,2) not null check (price_pct > 0),
  sort_order  smallint not null default 0,
  active      boolean  not null default true,
  created_at  timestamptz not null default now()
);

-- PLACEHOLDER PERCENTAGES — 55% and 75% came from the brief as a starting
-- rule, not from costed figures. Editable in the admin product form.
insert into public.product_sizes (id, label, volume_ml, price_pct, sort_order)
select * from (values
  (1, '35 ml',   35,  55.00, 1),
  (2, '50 ml',   50,  75.00, 2),
  (3, '100 ml', 100, 100.00, 3)
) as seed(id, label, volume_ml, price_pct, sort_order)
where not exists (select 1 from public.product_sizes);

-- ------------------------------------------------------------- variants ---
create table if not exists public.product_variants (
  id          bigint generated by default as identity primary key,
  product_id  bigint   not null references public.products(id) on delete cascade,
  size_id     smallint not null references public.product_sizes(id) on delete restrict,
  -- null = derive from products.price * product_sizes.price_pct
  price       integer  check (price is null or price >= 0),
  stock       integer  not null default 0 check (stock >= 0),
  sku         text,
  active      boolean  not null default true,
  created_at  timestamptz not null default now(),
  unique (product_id, size_id)
);

create index if not exists product_variants_product_idx on public.product_variants (product_id);
create index if not exists product_variants_stock_idx   on public.product_variants (stock);

-- Every product gets every active size. The base price already refers to the
-- 100 ml, so that variant inherits the stock the product is carrying today and
-- the smaller sizes start at zero: we know what stock exists, we do not know
-- what stock exists in a size that has never been sold. Inventing it would put
-- orders on the books that cannot be filled.
insert into public.product_variants (product_id, size_id, stock)
select p.id, s.id, case when s.volume_ml = 100 then coalesce(p.stock, 0) else 0 end
from public.products p
cross join public.product_sizes s
where s.active
on conflict (product_id, size_id) do nothing;

-- ------------------------------------------------------ stock roll-up ---
-- products.stock becomes the sum of its variants, maintained here rather than
-- by hand. Everything that already reads products.stock — the storefront's
-- esgotado badge, Stock, the low-stock count on Início — keeps working without
-- knowing variants exist.
create or replace function public.sync_product_stock()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target bigint := coalesce(new.product_id, old.product_id);
begin
  update public.products
     set stock = (
       select coalesce(sum(v.stock), 0)
       from public.product_variants v
       where v.product_id = target and v.active
     )
   where id = target;
  return null;
end;
$$;

drop trigger if exists product_variants_sync_stock on public.product_variants;
create trigger product_variants_sync_stock
  after insert or update or delete on public.product_variants
  for each row execute function public.sync_product_stock();

-- Bring every product's rollup in line with what was just seeded.
update public.products p
   set stock = (
     select coalesce(sum(v.stock), 0)
     from public.product_variants v
     where v.product_id = p.id and v.active
   );

-- -------------------------------------------------------------- policies ---
alter table public.product_sizes    enable row level security;
alter table public.product_variants enable row level security;

-- Prices and sizes are shown on every card; they are not secret.
drop policy if exists "anyone reads sizes" on public.product_sizes;
create policy "anyone reads sizes" on public.product_sizes
  for select to anon, authenticated using (true);

drop policy if exists "admins write sizes" on public.product_sizes;
create policy "admins write sizes" on public.product_sizes
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "anyone reads variants" on public.product_variants;
create policy "anyone reads variants" on public.product_variants
  for select to anon, authenticated using (true);

drop policy if exists "admins write variants" on public.product_variants;
create policy "admins write variants" on public.product_variants
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------- orders ---
-- The order line already snapshots name and price inside items jsonb; these two
-- put the size on the row itself so it survives a size being renamed or removed.
alter table public.orders
  add column if not exists has_variants boolean not null default false;
