-- B2 (fixação e projecção) and B3 (zonas de entrega).

-- ---------------------------------------------------- B2: fixação/projecção --
-- Stored as 1-5. The written label is generated from the number in one place
-- (js/main.js and admin/js/produtos.js share the same scale), so the wording
-- can change without touching data.
alter table public.products
  add column if not exists fixacao smallint,
  add column if not exists projecao smallint;

alter table public.products drop constraint if exists products_fixacao_check;
alter table public.products add constraint products_fixacao_check
  check (fixacao is null or fixacao between 1 and 5);

alter table public.products drop constraint if exists products_projecao_check;
alter table public.products add constraint products_projecao_check
  check (projecao is null or projecao between 1 and 5);

create index if not exists products_fixacao_idx on public.products (fixacao);

-- ------------------------------------------------------- B3: zonas de entrega --
-- Prices live in a table, not in code, because the brief is explicit that
-- changing a delivery price must never need a developer.
create table if not exists public.delivery_zones (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  -- "Fora de Luanda" has no fixed price: the order still goes through and the
  -- cost is agreed afterwards by direct contact.
  on_request boolean not null default false,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists delivery_zones_active_idx on public.delivery_zones (active, sort_order);

alter table public.delivery_zones enable row level security;

-- Readable by everyone: the cart shows the cheapest zone before sign-in, and
-- checkout needs the list. Prices are not secret.
drop policy if exists "anyone reads delivery zones" on public.delivery_zones;
create policy "anyone reads delivery zones" on public.delivery_zones
  for select to anon, authenticated using (true);

drop policy if exists "admins write delivery zones" on public.delivery_zones;
create policy "admins write delivery zones" on public.delivery_zones
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- PLACEHOLDER DATA — the district names are real Luanda areas but every PRICE
-- below is an example from the brief and must be confirmed before launch.
-- They are seeded as plausible values on purpose: a deliberately fake price
-- would make the checkout total impossible to test end to end. The admin panel
-- carries a visible warning until they are reviewed.
insert into public.delivery_zones (name, price, on_request, sort_order)
select * from (values
  ('Talatona',                   2500, false, 1),
  ('Kilamba / Camama',           3000, false, 2),
  ('Luanda Centro / Ingombota',  3500, false, 3),
  ('Viana / Cacuaco',            4500, false, 4),
  ('Fora de Luanda',                0, true,  5)
) as seed(name, price, on_request, sort_order)
where not exists (select 1 from public.delivery_zones);

-- The order keeps a snapshot of the zone name and the fee charged, so a later
-- price change never rewrites history. delivery_fee already exists.
alter table public.orders
  add column if not exists delivery_zone text,
  add column if not exists delivery_on_request boolean not null default false;

-- ------------------------------------------------------------- settings --
-- Free delivery above a configurable order value; zero or null disables it.
alter table public.payment_settings
  add column if not exists free_delivery_threshold numeric,
  add column if not exists free_delivery_active boolean not null default false;

-- The cart shows "entrega a partir de X" before the visitor signs in, and the
-- free-delivery rule has to be readable then too — but payment_settings holds
-- the IBAN and stays closed to anon. Same approach as site_banner: a view with
-- only the public-safe columns. Do not add payment columns here.
create or replace view public.site_delivery_settings
with (security_invoker = false) as
  select
    free_delivery_threshold,
    free_delivery_active
  from public.payment_settings
  where id = 1;

grant select on public.site_delivery_settings to anon, authenticated;

comment on view public.site_delivery_settings is
  'Public-safe slice of payment_settings: the free-delivery rule only. Never add payment columns here.';
