-- Contact form: questions submitted from contacto.html.
--
-- Anyone may write (a visitor asking a question hasn't necessarily got an
-- account), but only admins may read — otherwise the anon key would let any
-- visitor list everyone else's messages and email addresses.

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  subject text,
  message text not null,
  handled boolean not null default false
);

alter table public.contact_messages enable row level security;

-- Insert-only for the public. There is deliberately no matching select policy
-- for anon, so a submitter cannot read back what anyone (including themselves)
-- has sent.
drop policy if exists "anyone can submit a contact message" on public.contact_messages;
create policy "anyone can submit a contact message"
  on public.contact_messages for insert
  to anon, authenticated
  with check (true);

drop policy if exists "admins read contact messages" on public.contact_messages;
create policy "admins read contact messages"
  on public.contact_messages for select
  to authenticated
  using (public.is_admin());

drop policy if exists "admins update contact messages" on public.contact_messages;
create policy "admins update contact messages"
  on public.contact_messages for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create index if not exists contact_messages_created_at_idx
  on public.contact_messages (created_at desc);
