-- Campaigns: the thing that actually applies a discount, as opposed to the
-- banner, which is only a notice. A campaign chooses products three ways that
-- combine (everything / by category / hand-picked), carries one discount, and
-- turns itself on and off by date.

create table if not exists public.campaigns (
  id             bigint generated by default as identity primary key,
  name           text    not null,
  discount_type  text    not null check (discount_type in ('percentage', 'fixed')),
  discount_value numeric not null check (discount_value >= 0),

  -- Activity is derived from these, never from a flag someone has to remember
  -- to switch off.
  start_date date not null,
  end_date   date not null,

  -- The three ways of choosing, which are combined as a union. Hand-picked
  -- products live in campaign_products.
  target_all        boolean not null default false,
  target_categories text[]  not null default '{}',

  applies_to_amostras boolean not null default false,
  -- Whether a cupão can be used on top. Off by default: two discounts at once
  -- is rarely what anyone means.
  allow_coupons       boolean not null default false,

  -- Campaigns are archived, never deleted, so what ran and when stays on the
  -- record.
  archived   boolean not null default false,
  created_at timestamptz not null default now(),

  constraint campaigns_dates_check check (end_date >= start_date)
);

create table if not exists public.campaign_products (
  campaign_id bigint not null references public.campaigns(id) on delete cascade,
  product_id  bigint not null references public.products(id)  on delete cascade,
  primary key (campaign_id, product_id)
);

create index if not exists campaigns_active_idx on public.campaigns (archived, start_date, end_date);
create index if not exists campaign_products_product_idx on public.campaign_products (product_id);

-- ------------------------------------------------------------ resolving ---
-- Takes the targeting as it stands in the form, so the preview can be shown
-- before anything is saved. The three selectors are a union: "all feminino
-- plus these two others" is one campaign, not three.
create or replace function public.resolve_campaign_products(
  p_all        boolean default false,
  p_categories text[] default '{}',
  p_product_ids bigint[] default '{}'
)
returns table (
  id               bigint,
  name             text,
  category         text,
  price            integer,
  discount_percent numeric,
  amostra_enabled  boolean,
  amostra_price    integer
)
language sql
stable
security definer
set search_path to 'public'
as $function$
  select p.id, p.name, p.category, p.price, p.discount_percent,
         p.amostra_enabled, p.amostra_price
  from public.products p
  where p.archived = false
    and (
      coalesce(p_all, false)
      or p.category = any(coalesce(p_categories, '{}'))
      or p.id = any(coalesce(p_product_ids, '{}'))
    )
  order by p.name;
$function$;

-- Every product a saved campaign covers, used by the storefront view and by
-- the overlap check.
create or replace function public.campaign_product_ids(p_campaign_id bigint)
returns setof bigint
language sql
stable
security definer
set search_path to 'public'
as $function$
  select r.id
  from public.campaigns c
  cross join lateral public.resolve_campaign_products(
    c.target_all,
    c.target_categories,
    array(select cp.product_id from public.campaign_products cp where cp.campaign_id = c.id)
  ) r
  where c.id = p_campaign_id;
$function$;

-- ------------------------------------------------------------- conflicts ---
-- A product may only be in one campaign at a time. "At a time" means the date
-- ranges overlap, not that both exist — two campaigns in different months are
-- fine. p_campaign_id excludes the campaign being edited from its own check.
create or replace function public.campaign_conflicts(
  p_campaign_id bigint default null,
  p_start       date    default current_date,
  p_end         date    default current_date,
  p_all         boolean default false,
  p_categories  text[]  default '{}',
  p_product_ids bigint[] default '{}'
)
returns table (
  product_id    bigint,
  product_name  text,
  campaign_id   bigint,
  campaign_name text
)
language sql
stable
security definer
set search_path to 'public'
as $function$
  select r.id, r.name, c.id, c.name
  from public.resolve_campaign_products(p_all, p_categories, p_product_ids) r
  join public.campaigns c
    on c.archived = false
   and (p_campaign_id is null or c.id <> p_campaign_id)
   -- Two ranges overlap when each starts before the other ends.
   and c.start_date <= p_end
   and c.end_date   >= p_start
  where r.id in (select public.campaign_product_ids(c.id))
  order by r.name;
$function$;

-- ------------------------------------------------- what the shop reads ---
-- One row per product currently on promotion, with the discount to apply.
-- A product can only be in one live campaign, so distinct on is safe; it picks
-- the one that started most recently if the rule is ever breached.
create or replace view public.active_campaign_products
with (security_invoker = false) as
  select distinct on (r.id)
    r.id            as product_id,
    c.id            as campaign_id,
    c.name          as campaign_name,
    c.discount_type,
    c.discount_value,
    c.end_date,
    c.applies_to_amostras,
    c.allow_coupons
  from public.campaigns c
  cross join lateral public.resolve_campaign_products(
    c.target_all,
    c.target_categories,
    array(select cp.product_id from public.campaign_products cp where cp.campaign_id = c.id)
  ) r
  where c.archived = false
    and current_date between c.start_date and c.end_date
  order by r.id, c.start_date desc, c.id desc;

grant select on public.active_campaign_products to anon, authenticated;

-- ------------------------------------------------------------- policies ---
alter table public.campaigns         enable row level security;
alter table public.campaign_products enable row level security;

-- A running campaign is public information: it is printed on every affected
-- card. Reading the table directly is no more than reading the shelf.
drop policy if exists "anyone reads campaigns" on public.campaigns;
create policy "anyone reads campaigns" on public.campaigns
  for select to anon, authenticated using (true);

drop policy if exists "admins write campaigns" on public.campaigns;
create policy "admins write campaigns" on public.campaigns
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "anyone reads campaign products" on public.campaign_products;
create policy "anyone reads campaign products" on public.campaign_products
  for select to anon, authenticated using (true);

drop policy if exists "admins write campaign products" on public.campaign_products;
create policy "admins write campaign products" on public.campaign_products
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- -------------------------------------------------------------- banner ---
-- The banner can be attached to a campaign, and then comes and goes with it.
-- It still works on its own for announcements that have nothing to do with a
-- discount, which is why every one of these is nullable.
alter table public.payment_settings
  add column if not exists banner_campaign_id bigint references public.campaigns(id) on delete set null,
  add column if not exists banner_cta_label   text,
  add column if not exists banner_cta_url     text;
