-- Admin dashboard: the order workflow, its audit trail, and the fields the
-- dashboard needs to be a work surface rather than a report.
--
-- There is no payment gateway on this site. Every order needs a person to look
-- at a comprovativo, decide whether the money arrived, and only then release
-- the shipment. The status vocabulary below is that cycle, in order.

-- ---------------------------------------------------------------- orders ---
-- The state was previously spread across status + payment_status +
-- delivery_status, which meant the same order could read "pending" in one
-- column and "paid" in another. One column now carries the whole cycle.
alter table public.orders
  add column if not exists cancel_reason text,
  add column if not exists receipt_rejected_reason text,
  add column if not exists admin_notes text,
  add column if not exists archived boolean not null default false;

-- The old constraint has to go BEFORE the update: it only allowed the previous
-- vocabulary, so it would reject every new value the update writes.
alter table public.orders drop constraint if exists orders_status_check;

-- Existing rows mapped onto the new vocabulary. Orders still waiting are split
-- by whether a comprovativo actually arrived, which is the distinction the
-- whole dashboard turns on.
update public.orders set status = case
  when status in ('cancelled', 'refunded')            then 'cancelado'
  when status = 'delivered'                           then 'entregue'
  when status = 'shipped'                             then 'enviado'
  when status = 'processing'                          then 'em_preparacao'
  when status = 'confirmed' or payment_status = 'paid' then 'pagamento_confirmado'
  when receipt_url is not null and receipt_url <> ''  then 'comprovativo_recebido'
  else 'aguarda_pagamento'
end
where status not in ('aguarda_pagamento','comprovativo_recebido','pagamento_confirmado',
                     'em_preparacao','enviado','entregue','cancelado');

alter table public.orders add constraint orders_status_check check (status in (
  'aguarda_pagamento',
  'comprovativo_recebido',
  'pagamento_confirmado',
  'em_preparacao',
  'enviado',
  'entregue',
  'cancelado'
));

alter table public.orders alter column status set default 'aguarda_pagamento';

-- A cancellation always has to say why.
alter table public.orders drop constraint if exists orders_cancel_reason_check;
alter table public.orders add constraint orders_cancel_reason_check
  check (status <> 'cancelado' or (cancel_reason is not null and length(trim(cancel_reason)) > 0));

create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- ------------------------------------------------- order status history ---
-- Every status change, so the detail page can show who moved an order and when.
create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  created_at timestamptz not null default now()
);
create index if not exists order_status_history_order_idx
  on public.order_status_history (order_id, created_at desc);

alter table public.order_status_history enable row level security;
drop policy if exists "admins read order history" on public.order_status_history;
create policy "admins read order history" on public.order_status_history
  for select to authenticated using (public.is_admin());
drop policy if exists "admins write order history" on public.order_status_history;
create policy "admins write order history" on public.order_status_history
  for insert to authenticated with check (public.is_admin());

-- ------------------------------------------------------- activity log ---
-- Who did what, for when more than one person has access.
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action text not null,
  entity text,
  entity_id text,
  detail jsonb,
  created_at timestamptz not null default now()
);
create index if not exists activity_log_created_at_idx on public.activity_log (created_at desc);

alter table public.activity_log enable row level security;
drop policy if exists "admins read activity" on public.activity_log;
create policy "admins read activity" on public.activity_log
  for select to authenticated using (public.is_admin());
drop policy if exists "admins write activity" on public.activity_log;
create policy "admins write activity" on public.activity_log
  for insert to authenticated with check (public.is_admin());

-- -------------------------------------------------- contact messages ---
alter table public.contact_messages
  add column if not exists read_at timestamptz,
  add column if not exists admin_notes text,
  add column if not exists archived boolean not null default false;

-- --------------------------------------------------------- products ---
-- Which questionnaire answer each perfume maps to (see js/quiz.js), so the
-- recommendation is editable from the dashboard instead of inferred from text.
alter table public.products
  add column if not exists quiz_mood text,
  add column if not exists quiz_family text,
  add column if not exists quiz_occasion text,
  add column if not exists archived boolean not null default false;

-- ------------------------------------------------- store settings ---
-- The values that currently render as dashes on the live site. The IBAN in
-- particular has to be changeable without a developer.
alter table public.payment_settings
  add column if not exists store_phone text,
  add column if not exists store_email text,
  add column if not exists store_instagram text,
  add column if not exists banner_text text,
  add column if not exists banner_active boolean not null default false;
