// Country calling codes for the account phone field. ISO2 + Portuguese name + dial code.
const COUNTRY_CODES = [
  { iso: "AF", name: "Afeganistão", dial: "+93" },
  { iso: "ZA", name: "África do Sul", dial: "+27" },
  { iso: "AL", name: "Albânia", dial: "+355" },
  { iso: "DE", name: "Alemanha", dial: "+49" },
  { iso: "AD", name: "Andorra", dial: "+376" },
  { iso: "AO", name: "Angola", dial: "+244" },
  { iso: "AI", name: "Anguilla", dial: "+1264" },
  { iso: "AQ", name: "Antártida", dial: "+672" },
  { iso: "AG", name: "Antígua e Barbuda", dial: "+1268" },
  { iso: "SA", name: "Arábia Saudita", dial: "+966" },
  { iso: "DZ", name: "Argélia", dial: "+213" },
  { iso: "AR", name: "Argentina", dial: "+54" },
  { iso: "AM", name: "Armênia", dial: "+374" },
  { iso: "AW", name: "Aruba", dial: "+297" },
  { iso: "AU", name: "Austrália", dial: "+61" },
  { iso: "AT", name: "Áustria", dial: "+43" },
  { iso: "AZ", name: "Azerbaijão", dial: "+994" },
  { iso: "BS", name: "Bahamas", dial: "+1242" },
  { iso: "BH", name: "Bahrein", dial: "+973" },
  { iso: "BD", name: "Bangladesh", dial: "+880" },
  { iso: "BB", name: "Barbados", dial: "+1246" },
  { iso: "BE", name: "Bélgica", dial: "+32" },
  { iso: "BZ", name: "Belize", dial: "+501" },
  { iso: "BJ", name: "Benin", dial: "+229" },
  { iso: "BY", name: "Bielorrússia", dial: "+375" },
  { iso: "BO", name: "Bolívia", dial: "+591" },
  { iso: "BA", name: "Bósnia e Herzegovina", dial: "+387" },
  { iso: "BW", name: "Botsuana", dial: "+267" },
  { iso: "BR", name: "Brasil", dial: "+55" },
  { iso: "BN", name: "Brunei", dial: "+673" },
  { iso: "BG", name: "Bulgária", dial: "+359" },
  { iso: "BF", name: "Burquina Faso", dial: "+226" },
  { iso: "BI", name: "Burundi", dial: "+257" },
  { iso: "BT", name: "Butão", dial: "+975" },
  { iso: "CV", name: "Cabo Verde", dial: "+238" },
  { iso: "CM", name: "Camarões", dial: "+237" },
  { iso: "KH", name: "Camboja", dial: "+855" },
  { iso: "CA", name: "Canadá", dial: "+1" },
  { iso: "QA", name: "Catar", dial: "+974" },
  { iso: "KZ", name: "Cazaquistão", dial: "+7" },
  { iso: "TD", name: "Chade", dial: "+235" },
  { iso: "CL", name: "Chile", dial: "+56" },
  { iso: "CN", name: "China", dial: "+86" },
  { iso: "CY", name: "Chipre", dial: "+357" },
  { iso: "CO", name: "Colômbia", dial: "+57" },
  { iso: "KM", name: "Comores", dial: "+269" },
  { iso: "CG", name: "Congo-Brazzaville", dial: "+242" },
  { iso: "CD", name: "Congo-Kinshasa (RDC)", dial: "+243" },
  { iso: "KP", name: "Coreia do Norte", dial: "+850" },
  { iso: "KR", name: "Coreia do Sul", dial: "+82" },
  { iso: "CI", name: "Costa do Marfim", dial: "+225" },
  { iso: "CR", name: "Costa Rica", dial: "+506" },
  { iso: "HR", name: "Croácia", dial: "+385" },
  { iso: "CU", name: "Cuba", dial: "+53" },
  { iso: "CW", name: "Curaçao", dial: "+599" },
  { iso: "DK", name: "Dinamarca", dial: "+45" },
  { iso: "DJ", name: "Djibuti", dial: "+253" },
  { iso: "DM", name: "Dominica", dial: "+1767" },
  { iso: "EG", name: "Egito", dial: "+20" },
  { iso: "SV", name: "El Salvador", dial: "+503" },
  { iso: "AE", name: "Emirados Árabes Unidos", dial: "+971" },
  { iso: "EC", name: "Equador", dial: "+593" },
  { iso: "ER", name: "Eritreia", dial: "+291" },
  { iso: "SK", name: "Eslováquia", dial: "+421" },
  { iso: "SI", name: "Eslovênia", dial: "+386" },
  { iso: "ES", name: "Espanha", dial: "+34" },
  { iso: "US", name: "Estados Unidos", dial: "+1" },
  { iso: "EE", name: "Estônia", dial: "+372" },
  { iso: "SZ", name: "Essuatíni", dial: "+268" },
  { iso: "ET", name: "Etiópia", dial: "+251" },
  { iso: "FJ", name: "Fiji", dial: "+679" },
  { iso: "PH", name: "Filipinas", dial: "+63" },
  { iso: "FI", name: "Finlândia", dial: "+358" },
  { iso: "FR", name: "França", dial: "+33" },
  { iso: "GA", name: "Gabão", dial: "+241" },
  { iso: "GM", name: "Gâmbia", dial: "+220" },
  { iso: "GH", name: "Gana", dial: "+233" },
  { iso: "GE", name: "Geórgia", dial: "+995" },
  { iso: "GI", name: "Gibraltar", dial: "+350" },
  { iso: "GD", name: "Granada", dial: "+1473" },
  { iso: "GR", name: "Grécia", dial: "+30" },
  { iso: "GL", name: "Groenlândia", dial: "+299" },
  { iso: "GP", name: "Guadalupe", dial: "+590" },
  { iso: "GU", name: "Guam", dial: "+1671" },
  { iso: "GT", name: "Guatemala", dial: "+502" },
  { iso: "GY", name: "Guiana", dial: "+592" },
  { iso: "GF", name: "Guiana Francesa", dial: "+594" },
  { iso: "GN", name: "Guiné", dial: "+224" },
  { iso: "GQ", name: "Guiné Equatorial", dial: "+240" },
  { iso: "GW", name: "Guiné-Bissau", dial: "+245" },
  { iso: "HT", name: "Haiti", dial: "+509" },
  { iso: "HN", name: "Honduras", dial: "+504" },
  { iso: "HK", name: "Hong Kong", dial: "+852" },
  { iso: "HU", name: "Hungria", dial: "+36" },
  { iso: "YE", name: "Iêmen", dial: "+967" },
  { iso: "MP", name: "Ilhas Marianas do Norte", dial: "+1670" },
  { iso: "MH", name: "Ilhas Marshall", dial: "+692" },
  { iso: "SB", name: "Ilhas Salomão", dial: "+677" },
  { iso: "IN", name: "Índia", dial: "+91" },
  { iso: "ID", name: "Indonésia", dial: "+62" },
  { iso: "IR", name: "Irã", dial: "+98" },
  { iso: "IQ", name: "Iraque", dial: "+964" },
  { iso: "IE", name: "Irlanda", dial: "+353" },
  { iso: "IS", name: "Islândia", dial: "+354" },
  { iso: "IL", name: "Israel", dial: "+972" },
  { iso: "IT", name: "Itália", dial: "+39" },
  { iso: "JM", name: "Jamaica", dial: "+1876" },
  { iso: "JP", name: "Japão", dial: "+81" },
  { iso: "JE", name: "Jersey", dial: "+44" },
  { iso: "JO", name: "Jordânia", dial: "+962" },
  { iso: "KI", name: "Kiribati", dial: "+686" },
  { iso: "KW", name: "Kuwait", dial: "+965" },
  { iso: "LA", name: "Laos", dial: "+856" },
  { iso: "LS", name: "Lesoto", dial: "+266" },
  { iso: "LV", name: "Letônia", dial: "+371" },
  { iso: "LB", name: "Líbano", dial: "+961" },
  { iso: "LR", name: "Libéria", dial: "+231" },
  { iso: "LY", name: "Líbia", dial: "+218" },
  { iso: "LI", name: "Liechtenstein", dial: "+423" },
  { iso: "LT", name: "Lituânia", dial: "+370" },
  { iso: "LU", name: "Luxemburgo", dial: "+352" },
  { iso: "MO", name: "Macau", dial: "+853" },
  { iso: "MK", name: "Macedônia do Norte", dial: "+389" },
  { iso: "MG", name: "Madagascar", dial: "+261" },
  { iso: "MY", name: "Malásia", dial: "+60" },
  { iso: "MW", name: "Malawi", dial: "+265" },
  { iso: "MV", name: "Maldivas", dial: "+960" },
  { iso: "ML", name: "Mali", dial: "+223" },
  { iso: "MT", name: "Malta", dial: "+356" },
  { iso: "MA", name: "Marrocos", dial: "+212" },
  { iso: "MQ", name: "Martinica", dial: "+596" },
  { iso: "MU", name: "Maurícia", dial: "+230" },
  { iso: "MR", name: "Mauritânia", dial: "+222" },
  { iso: "YT", name: "Mayotte", dial: "+262" },
  { iso: "MX", name: "México", dial: "+52" },
  { iso: "MM", name: "Mianmar", dial: "+95" },
  { iso: "FM", name: "Micronésia", dial: "+691" },
  { iso: "MZ", name: "Moçambique", dial: "+258" },
  { iso: "MD", name: "Moldávia", dial: "+373" },
  { iso: "MC", name: "Mônaco", dial: "+377" },
  { iso: "MN", name: "Mongólia", dial: "+976" },
  { iso: "ME", name: "Montenegro", dial: "+382" },
  { iso: "MS", name: "Montserrat", dial: "+1664" },
  { iso: "NA", name: "Namíbia", dial: "+264" },
  { iso: "NR", name: "Nauru", dial: "+674" },
  { iso: "NP", name: "Nepal", dial: "+977" },
  { iso: "NI", name: "Nicarágua", dial: "+505" },
  { iso: "NE", name: "Níger", dial: "+227" },
  { iso: "NG", name: "Nigéria", dial: "+234" },
  { iso: "NU", name: "Niue", dial: "+683" },
  { iso: "NO", name: "Noruega", dial: "+47" },
  { iso: "NC", name: "Nova Caledônia", dial: "+687" },
  { iso: "NZ", name: "Nova Zelândia", dial: "+64" },
  { iso: "OM", name: "Omã", dial: "+968" },
  { iso: "NL", name: "Países Baixos", dial: "+31" },
  { iso: "PW", name: "Palau", dial: "+680" },
  { iso: "PS", name: "Palestina", dial: "+970" },
  { iso: "PA", name: "Panamá", dial: "+507" },
  { iso: "PG", name: "Papua-Nova Guiné", dial: "+675" },
  { iso: "PK", name: "Paquistão", dial: "+92" },
  { iso: "PY", name: "Paraguai", dial: "+595" },
  { iso: "PE", name: "Peru", dial: "+51" },
  { iso: "PF", name: "Polinésia Francesa", dial: "+689" },
  { iso: "PL", name: "Polônia", dial: "+48" },
  { iso: "PR", name: "Porto Rico", dial: "+1787" },
  { iso: "PT", name: "Portugal", dial: "+351" },
  { iso: "KE", name: "Quênia", dial: "+254" },
  { iso: "KG", name: "Quirguistão", dial: "+996" },
  { iso: "GB", name: "Reino Unido", dial: "+44" },
  { iso: "CF", name: "República Centro-Africana", dial: "+236" },
  { iso: "CZ", name: "República Tcheca", dial: "+420" },
  { iso: "DO", name: "República Dominicana", dial: "+1809" },
  { iso: "RE", name: "Reunião", dial: "+262" },
  { iso: "RO", name: "Romênia", dial: "+40" },
  { iso: "RW", name: "Ruanda", dial: "+250" },
  { iso: "RU", name: "Rússia", dial: "+7" },
  { iso: "EH", name: "Saara Ocidental", dial: "+212" },
  { iso: "WS", name: "Samoa", dial: "+685" },
  { iso: "AS", name: "Samoa Americana", dial: "+1684" },
  { iso: "SM", name: "San Marino", dial: "+378" },
  { iso: "SH", name: "Santa Helena", dial: "+290" },
  { iso: "LC", name: "Santa Lúcia", dial: "+1758" },
  { iso: "KN", name: "São Cristóvão e Neves", dial: "+1869" },
  { iso: "ST", name: "São Tomé e Príncipe", dial: "+239" },
  { iso: "VC", name: "São Vicente e Granadinas", dial: "+1784" },
  { iso: "SN", name: "Senegal", dial: "+221" },
  { iso: "SL", name: "Serra Leoa", dial: "+232" },
  { iso: "RS", name: "Sérvia", dial: "+381" },
  { iso: "SC", name: "Seychelles", dial: "+248" },
  { iso: "SG", name: "Singapura", dial: "+65" },
  { iso: "SY", name: "Síria", dial: "+963" },
  { iso: "SO", name: "Somália", dial: "+252" },
  { iso: "LK", name: "Sri Lanka", dial: "+94" },
  { iso: "SD", name: "Sudão", dial: "+249" },
  { iso: "SS", name: "Sudão do Sul", dial: "+211" },
  { iso: "SE", name: "Suécia", dial: "+46" },
  { iso: "CH", name: "Suíça", dial: "+41" },
  { iso: "SR", name: "Suriname", dial: "+597" },
  { iso: "TH", name: "Tailândia", dial: "+66" },
  { iso: "TW", name: "Taiwan", dial: "+886" },
  { iso: "TJ", name: "Tajiquistão", dial: "+992" },
  { iso: "TZ", name: "Tanzânia", dial: "+255" },
  { iso: "TL", name: "Timor-Leste", dial: "+670" },
  { iso: "TG", name: "Togo", dial: "+228" },
  { iso: "TO", name: "Tonga", dial: "+676" },
  { iso: "TT", name: "Trinidad e Tobago", dial: "+1868" },
  { iso: "TN", name: "Tunísia", dial: "+216" },
  { iso: "TM", name: "Turcomenistão", dial: "+993" },
  { iso: "TR", name: "Turquia", dial: "+90" },
  { iso: "TV", name: "Tuvalu", dial: "+688" },
  { iso: "UA", name: "Ucrânia", dial: "+380" },
  { iso: "UG", name: "Uganda", dial: "+256" },
  { iso: "UY", name: "Uruguai", dial: "+598" },
  { iso: "UZ", name: "Uzbequistão", dial: "+998" },
  { iso: "VU", name: "Vanuatu", dial: "+678" },
  { iso: "VA", name: "Vaticano", dial: "+379" },
  { iso: "VE", name: "Venezuela", dial: "+58" },
  { iso: "VN", name: "Vietnã", dial: "+84" },
  { iso: "ZM", name: "Zâmbia", dial: "+260" },
  { iso: "ZW", name: "Zimbábue", dial: "+263" },
];
